<?php 
    $default_img = base_url('assets/'.$this->config->item('company_dir').'/print/header.png');
    $brand_id = get_brand_id($estimate_data, $client_data);
    $estimate_logo = get_brand_logo($brand_id, 'main_logo_file', $default_img);
    $estimate_terms = get_estimate_terms($brand_id);
?>
<pagebreak>
	<div class="holder p_top_" style="margin-left: 342px; margin-top: 0px;"><img src="<?php echo $estimate_logo; ?>" width="482" height="85"
	                       style="<?php echo $this->config->item('company_header_pdf_small_logo_styles'); ?>"    class="p-top-20"></div>
	<div class="title m_min_50" style="margin-top: -40px;">Terms and Conditions</div>
	<br>
	<?php if(!strip_tags($estimate_terms, ['img'])): ?>
	<div class="title_1">TERMS:</div>
	<div class="des_1">PAYMENT DUE IN FULL UPON JOB COMPLETION UNLESS OTHER ARRANGEMENTS HAVE BEEN MADE PRIOR TO START OF JOB. FINANCE CHARGES OF 1.5% PER MONTH WILL BE ADDED TO BILL. PLEASE PAY FOREMAN AT JOB COMPLETION.
	IN THE EVENT OF A DEFAULT IN THE PAYMENT OF THE AMOUNT DUE HEREUNDER, LEWIS TREE SERVICE, INC. SHALL BE ENTITLED TO COLLECT ALL REASONABLE COSTS OF COLLECTION, INCLUDING BUT NOT LIMITED TO, A REASONABLE ATTORNEY'S FEE.
	NOTES: TIME AND MATERIALS (T&M) INCLUDES TRAVEL TIME TO AND FROM LEWIS TREE SERVICE, INC. AND TIME IS BILLED IN WHOLE HOUR INCREMENTS.
	LEWIS TREE SERVICE, INC. IS NOT RESPONSIBLE FOR BROKEN SPRINKLER OR UTILITY LINES, OR SEPTIC TANKS THAT HAVE NOT BEEN LOCATED AND MARKED BY THE HOMEOWNER, PROPERTY MANAGER OR AGENT.
	LEWIS TREE SERVICE, INC. IS NOT RESPONSIBLE FOR OBTAINING ANY REQUIRED PERMITS FROM STATE, COUNTY OR LOCAL AUTHORITIES.
	LEWIS TREE SERVICE, INC. IS FURTHERMORE NOT RESPONSIBLE FOR ANY INCIDENTAL DAMAGES TO PROPERTY OR PERSON WHICH ARE NOT THE FAULT OF LEWIS TREE SERVICE, INC. SUCH DAMAGES INCLUDE, WITHOUT LIMITATION, DAMAGES CAUSED BY TREE AND/OR ROOT FAILURE FROM PRUNING OR CUTTING INCLUDING EROSION AND/OR FALLING TREES OR BRANCHES. HOMEOWNER ACKNOWLEDGES THAT TREES AND BRANCHES CAN AND DO FALL WITHOUT WARNING AT ANY TIME, AND THAT ANY AND ALL DAMAGES CAUSED THEREBY, INCLUDING INJURY TO PERSONS AND DAMAGE TO PROPERTY, ARE NOT THE RESPONSIBILITY OF LEWIS TREE SERVICE, INC.</div>

	<div class="title_1">NOTICE TO OWNER:</div>
	<div class="des_1">IN COMPLIANCE WITH CONTRACTOR'S LICENSE LAW SECTION 7018.5, (B&P CODE, DIV. 3, CHAP. 9) THIS IS TO INFORM YOU THAT UNDER THE MECHANICS' LIEN LAW (CALIFORNIA CODE OF CIVIL PROCEDURES SECTION 1181 ER SEQ.) ANY CONTRACTOR, SUBCONTRACTOR, LABORER, SUPPLIER, OR OTHER PERSON WHO HELPS TO IMPROVE YOUR PROPERTY BUT IS NOT PAID FOR HIS WORK OR SUPPLIES, HAS A RIGHT TO ENFORCE A CLAIM AGAINST YOUR PROPERTY. THIS MEANS THAT AFTER A COURT HEARING, YOUR PROPERTY COULD BE SOLD BY A COURT AND THE PROCEEDS OF THE SALE USED TO SATISFY THE INDEBTEDNESS. THIS CAN HAPPEN EVEN IF YOU PAID YOUR OWN CONTRACTOR, IN FULL, IF THE SUBCONTRACTOR, LABORER, OR SUPPLIER REMAINS UNPAID.
	STATE LAW REQUIRES ANYONE WHO CONTRACTS TO DO CONSTRUCTION WORK TO BE LICENSED BY THE CONTRACTORS' STATE LICENSE BOARD IN THE LICENSE CATEGORY IN WHICH THE CONTRACTOR IS GOING TO BE WORKING - IF THE TOTAL PRICE OF THE JOB IS $500 OR MORE (INCLUDING LABOR AND MATERIALS).
	LICENSED CONTRACTORS ARE REGULATED BY LAWS DESIGNED TO PROTECT THE PUBLIC. IF YOU CONTRACT WITH SOMEONE WHO DOES NOT HAVE A LICENSE, THE CONTRACTORS' STATE LICENSE BOARD MAY BE UNABLE TO ASSIST YOU WITH A COMPLAINT. YOUR ONLY REMEDY AGAINST AN UNLICENSED CONTRACTOR MAY BE IN CIVIL COURT, AND YOU MAY BE LIABLE FOR DAMAGES ARISING OUT OF ANY INJURIES TO THE CONTRACTOR OR HIS OR HER EMPLOYEES.
	YOU MAY CONTACT THE CONTRACTORS' STATE LICENSE BOARD TO FIND OUT IF THIS CONTRACTOR HAS A VALID LICENSE. THE BOARD HAS COMPLETE INFORMATION ON THE HISTORY OF LICENSED CONTRACTORS, INCLUDING ANY SUSPENSIONS, REVOCATIONS, JUDGEMENTS, AND CITATIONS. THE BOARD HAS OFFICES THROUGHOUT CALIFORNIA. PLEASE CHECK THE GOVERNMENT PAGES OF THE WHITE PAGES FOR THE OFFICE NEAREST YOU (OR CALL 1-800-321-CSLB FOR MORE INFORMATION).</div>


	<div class="title_1">NOTICE OF CANCELLATION:</div>
	<div class="des_1">YOU MAY CANCEL THIS CONTRACT WITHOUT ANY OBLIGATION OR PENALTY WITHIN THREE BUSINESS DAYS OF THE AUTHORIZATION DATE. TO CANCEL, MAIL A SIGNED AND DATED STATEMENT OF CANCELLATION TO 1500 BROMMER STREET, SANTA CRUZ, CA 95062 AND INFORM THE OFFICE AT 831-476-1200.</div>

	<?php else: ?>
        <?php echo $estimate_terms; ?>
    <?php endif; ?>
    
	<?php $brand_address = brand_address($brand_id); ?>
   	<?php if($brand_address): ?>
   		<span class="green">ADDRESS:</span>&nbsp;<?php echo $brand_address; ?>&nbsp;<span class="green">OFFICE:</span>&nbsp;<?php echo brand_phone($brand_id); ?>&nbsp;<span class="green">EMAIL:</span>&nbsp;<?php echo brand_email($brand_id); ?>
    <?php else: ?>
		<div class="address" style="position: absolute; bottom: 20px; right: 0; left: 0;">
			<?php echo $this->config->item('footer_pdf_address'); ?>
		</div>
	<?php endif; ?>
