<?php

class Mdl_jobs extends JR_Model
{
    protected $_table = 'jobs';
    protected $primary_key = 'job_id';

    public function __construct()
    {
        parent::__construct();
    }

    public function get_all()
    {
        return parent::get_all(); // TODO: Change the autogenerated stub
    }

    public function get_failed()
    {
        return '`job_is_completed` = 0 AND `job_attempts` != 0 AND `job_reserved_at` != 0';
    }

    public function get_completed()
    {
        return '`job_is_completed` = 1 AND `job_attempts` != 0';
    }

    public function get_free()
    {
        return '`job_is_completed` = 0 AND `job_reserved_at` = 0';
    }

    public function like($column, $value)
    {
        $this->_database->like($column, $value);

        return $this;
    }

    public function or_like($column, $value)
    {
        $this->_database->or_like($column, $value);

        return $this;
    }

    public function query($sql)
    {
        return $this->_database->query($sql)->result();
    }

    public function where($sql, $value, $protect = true)
    {
        if ($protect === false)
            $this->_database->where($sql, $value, $protect);
        else
            $this->_database->where($sql, $value);

        return $this;
    }
}
