<?php if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}
$config['profiler'] = true;
$config['composer_autoload'] = FCPATH . 'vendor/autoload.php';
$config['migration_table'] = 'new_migrations';
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
$segments = array();
$config['base_url'] = "";
if (isset($_SERVER['REQUEST_URI'])) {
    $segments = explode('/', ltrim($_SERVER['REQUEST_URI'], '/'));
}

$protocol = 'http';
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
    $protocol = 'https';
}

if (isset($_SERVER['HTTP_HOST'])) {
    $config['base_url'] = $protocol . "://" . $_SERVER['HTTP_HOST'] . "/";
} else {
    $config['base_url'] = "https://td.onlineoffice.io/";
}
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';
/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol'] = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = true;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-?=(),+';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = true;
$config['enable_query_strings'] = false;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 4;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'gister';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'treedoctors_session';
$config['sess_expiration'] = 18000;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = false;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = false;

//$config['sess_cookie_name'] = 'treedoctors_session';
//$config['sess_expiration'] = 18000;
//$config['sess_expire_on_close'] = true;
//$config['sess_encrypt_cookie'] = true;
//$config['sess_use_database'] = false;
//$config['sess_table_name'] = 'ci_sessions';
//$config['sess_match_ip'] = false;
//$config['sess_match_useragent'] = true;
//$config['sess_time_to_update'] = 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix'] = "";
$config['cookie_domain'] = "";
$config['cookie_path'] = "/";
$config['cookie_secure'] = false;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = true;
/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = false;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = false;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'gmt';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = false;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

$config['global_xss_filtering_disabled'] = array('administration/ajax_save_template', 'clients/ajax_send_email');

/*
|--------------------------------------------------------------------------
| Google Service Account (Gmail)
|--------------------------------------------------------------------------
|
|
|
|
 */
$config['service_email_address'] = '729138097020-kd8mmg4ahah5u3bnqnefrcjo2v3hro6j@developer.gserviceaccount.com';
$config['service_cert_path'] = './uploads/treedoctors-c6f443f9efc0.p12';
$config['account_email_address'] = 'info@treedoctors.ca';
$config['office_address'] = '425 Kipling Ave';
$config['office_region'] = 'Etobicoke';
$config['office_city'] = 'Toronto';
$config['office_state'] = 'Ontario';
$config['office_zip'] = 'M8Z 5C8';
$config['office_address_map'] = '425+Kipling+Avenue+Toronto+ON+M8Z+5C7';
$config['office_description'] = '(south-east corner of Kipling and&nbsp;Horner)';

$config['office_country'] = 'Canada';
$config['office_phone'] = '+14162018000';
$config['office_phone_mask'] = '(416) 201-8000';
$config['office_fax'] = '647.435.3439';
$config['company_site'] = 'https://treedoctors.ca';
$config['company_site_http'] = 'http://treedoctors.ca';
$config['company_site_name'] = 'treedoctors.ca';
$config['company_site_name_upper'] = 'TreeDoctors.ca';

$config['footer_pdf_address'] = '<span class="green">ADDRESS: </span>' . $config['office_address'] . ' ' . $config['office_city'] . ', ' . $config['office_state'] . ' ' . $config['office_zip'] . ' <span class="green">OFFICE: </span>' . $config['office_phone_mask'] . ' <span class="green">WEB: </span> ' . $config['company_site_name_upper'];
$config['per_page_notes'] = 200;

$config['smtp_domains'] = ['hotmail.com', 'live.com', 'live.ca', 'msn.com', 'live.ru', 'outlook.com'];
$config['smtp_mail']['protocol'] = 'smtp';
$config['smtp_mail']['mailtype'] = 'html';
$config['smtp_mail']['smtp_host'] = 'ssl://smtp.gmail.com';
$config['smtp_mail']['smtp_port'] = '465';
$config['smtp_mail']['smtp_user'] = 'info@treedoctors.ca';
$config['smtp_mail']['smtp_pass'] = '53bhUCG92';
$config['gmaps_key'] = 'AIzaSyDJgAJg7KOCgq1V9yiCu0OutofbBNbsvFQ'; //NEW DV 'AIzaSyC27mDdTvOzlga3ZDEoqOfaOeIGgMi-j7Y'; NEW DV\\ //'AIzaSyAwMbzxEHnKw2frNAexNCbUd_Zp1Osy2ME';//(date('H') < '13') ? 'AIzaSyAwMbzxEHnKw2frNAexNCbUd_Zp1Osy2ME' : 'AIzaSyB8R2MPS7Wk_VTIw-L6eMl2LA5WFtH8Vcc'; //'AIzaSyBDUPTmUYuYnv9r8d6-TXanSefGZclfKTw';

$config['refferenced_by'] = [
    'no_info_provided' => 'No Info Provided',
    'google_search' => 'Google Search',
    'yellow_pages' => 'Yellow Pages',
    'facebook' => 'Facebook',
    'bing' => 'Bing',
    'homestars' => 'Homestars',
    'houzz' => 'Houzz',
    'kijiji' => 'Kijiji',
    'craigslist' => 'Craigslist',
    'the_guardian' => 'The Guardian, Toronto.com',
    'print' => 'Print, Flyers, etc',
    'tree_fellers' => 'Tree Fellers',
    'office_sign' => 'Office Sign',
    'calling_previous_clients' => 'Calling Previous Clients',
    'arborist_reporter' => 'Arborist Reporter',
    'existing_client' => 'Existing Client',
    'vehicle_sign' => 'Vehicle Sign',
    'friend_or_neighbor' => 'Friend Or Neighbor',
    'client' => 'Client',
    'user' => 'Employee',
    'other' => 'Other',
];

$config['followup_modules'] = [
    'leads' => [
        'name' => 'Leads',
        'number' => 1,
        'id_field_name' => 'lead_id',
        'no_field_name' => 'lead_no',
        'action_name' => 'edit',
        'status_field_name' => 'status',
        'reasons' => [],
        'statuses' => [
            'New' => 'New',
            'For Approval' => 'For Approval',
            'Already Done' => 'Already Done',
            'No Go' => 'No Go',
        ],
    ],
    'estimates' => [
        'name' => 'Estimates',
        'number' => 2,
        'id_field_name' => 'estimate_id',
        'no_field_name' => 'estimate_no',
        'action_name' => 'profile',
        'status_field_name' => 'status',
        'reasons' => [],
        'statuses' => [
            '1' => 'New',
            '2' => 'Sent for approval',
            '3' => 'Pending approval',
            '4' => 'Declined',
            '6' => 'Confirmed',
            '7' => 'Contact the client',
            '8' => 'Thinking- No Follow Up Needed',
        ],
    ],
    'invoices' => [
        'name' => 'Invoices',
        'number' => 3,
        'id_field_name' => 'id',
        'no_field_name' => 'invoice_no',
        'action_name' => 'profile',
        'status_field_name' => 'in_status',
        'reasons' => [],
        'statuses' => [
            'Issued' => 'Issued',
            'Sent' => 'Sent',
            'Overdue' => 'Overdue',
            'Paid' => 'Paid',
        ],
    ],
    'schedule' => [
        'name' => 'Schedule Event',
        'number' => 4,
        'id_field_name' => 'id',
        'no_field_name' => 'workorder_no',
        'action_name' => 'profile',
        'status_field_name' => 'wo_status',
        'reasons' => [],
        'statuses' => [
            '7' => 'Scheduled - Confirmed',
            '48' => 'Scheduled - Confirmed today only'
            /*'60' => 'PHC Spring 2019',
            '59' => 'Need to Get Locates',
            '49' => 'Confirmed for approval',
            '48' => 'Scheduled - Confirmed today only',
            '1' => 'Confirmed',
            '7' => 'Scheduled - Confirmed',
            '6' => 'Scheduled - Pending',
            '8' => 'Stump Grinding',
            '46' => 'Firewood delivery',
            '55' => 'Arborist consultation',
            '58' => 'Arborist Supervision',
            '45' => 'Xmass Lights Instalation',
            '41' => 'Confirmed EMERGENCY',
            '44' => 'TPZ',
            '3' => 'C-AR in Progress',
            '39' => 'AR in Progress',
            '5' => 'Exemption',
            '2' => 'City Permits - Exemptions',
            '4' => 'City Permits',
            '11' => 'Unfinished',
            '10' => 'Wood Pickup',
            '13' => 'Complains - Tree work',
            '12' => 'Complains - Damages',
            '57' => 'Complains - Other',
            '15' => 'On hold',
            '16' => 'Dormant Oil',
            '54' => 'ImaJet',
            '17' => 'Fertilizing Fall 2018',
            '50' => 'Planting Fall 2018',
            '0' => 'Finished',
            '14' => 'Repair',
            '51' => 'Acecap',
            '37' => 'Locates - Pending',
            '36' => 'Blue Bird Stumper'*/
        ],
    ],
    'client_tasks' => [
        'name' => 'Client Tasks',
        'number' => 5,
        'id_field_name' => 'task_id',
        'no_field_name' => 'task',
        'action_name' => '',
        'status_field_name' => 'task_status',
        'reasons' => [],
        'statuses' => [
            '2' => 'Construction Arborist Report',
            '3' => 'Regular Arborist Report',
            '4' => 'Exemption',
            '5' => 'Payment Follow Up Visit',
            '6' => 'Repair Assessment',
            '7' => 'Meeting with a client',
            '8' => 'Secondary visit.',
            '9' => 'Follow up call',
            '10' => 'Office Related Task',
            '11' => 'Arborist Supervision'
            /*'60' => 'PHC Spring 2019',
            '59' => 'Need to Get Locates',
            '49' => 'Confirmed for approval',
            '48' => 'Scheduled - Confirmed today only',
            '1' => 'Confirmed',
            '7' => 'Scheduled - Confirmed',
            '6' => 'Scheduled - Pending',
            '8' => 'Stump Grinding',
            '46' => 'Firewood delivery',
            '55' => 'Arborist consultation',
            '58' => 'Arborist Supervision',
            '45' => 'Xmass Lights Instalation',
            '41' => 'Confirmed EMERGENCY',
            '44' => 'TPZ',
            '3' => 'C-AR in Progress',
            '39' => 'AR in Progress',
            '5' => 'Exemption',
            '2' => 'City Permits - Exemptions',
            '4' => 'City Permits',
            '11' => 'Unfinished',
            '10' => 'Wood Pickup',
            '13' => 'Complains - Tree work',
            '12' => 'Complains - Damages',
            '57' => 'Complains - Other',
            '15' => 'On hold',
            '16' => 'Dormant Oil',
            '54' => 'ImaJet',
            '17' => 'Fertilizing Fall 2018',
            '50' => 'Planting Fall 2018',
            '0' => 'Finished',
            '14' => 'Repair',
            '51' => 'Acecap',
            '37' => 'Locates - Pending',
            '36' => 'Blue Bird Stumper'*/
        ],
    ],
    'employees' => [
        'name' => 'Employees',
        'number' => 5,
        'id_field_name' => '',
        'no_field_name' => '',
        'action_name' => '',
        'status_field_name' => '',
        'reasons' => [],
        'statuses' => [],
    ],
    'users' => [
        'name' => 'Users',
        'number' => 6,
        'id_field_name' => '',
        'no_field_name' => '',
        'action_name' => '',
        'status_field_name' => '',
        'reasons' => [],
        'statuses' => [],
    ],
];

$config['default_signature'] = '<table width="100%" style="border-spacing:0;color:#474a5d;margin: 0 auto;"><tbody><tr><td class="inner contents" style="padding-top:0;padding-bottom:10px;padding-right:0px;padding-left:0px;text-align:left;"><p style="font-size:18px;"><span lang="EN-CA" style="font-size:12px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d">Kind regards,</span></p><p style="font-size:18px;"><span style="font-family:AvenirNextLTPro-Regular,Arial,sans-serif;font-size:12px">Tree Doctors Arborist Team</span><br></p><span lang="EN-CA" style="font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d"><a href="tel:416.201.8000" value="+14162018000" style="font-size:12px;color:#474a5d" target="_blank">416.201.8000</a><span style="font-size:12px;"> |</span><b style="font-size:12px;"> </b><span style="font-size:12px;">Fax: </span><a href="tel:647.435.3439" value="+16474353439" style="font-size:12px;color:#474a5d" target="_blank">647.435.3439</a><span style="font-size:12px;"> |</span><b style="font-size:12px;"> </b><span style="font-size:12px;">TreeDoctors.ca</span><span style="font-size:12px;"><br></span></span><span style="color:#474a5d"><font face="Arial, sans-serif"><span style="font-size:12px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d"><a style="color:#474a5d" href="https://maps.google.com/?q=425+Kipling+Ave.+Toronto+M8Z+5C7">425 Kipling Ave. Toronto M8Z 5C7</a></span></font></span><span style="color:#474a5d"><font face="Arial, sans-serif"><span style="font-size:18px;"><br></span></font></span><span style="color:#474a5d"><font face="Arial, sans-serif"><span style="font-size:18px;"><br></span></font></span><span lang="EN-CA" style="font-size:18px;font-family:AvenirNext-Medium, Arial,sans-serif;color:#474a5d">Follow our latest news…</span></p><p style="font-size:18px;"><a href="http://twitter.com/treedoctorsca" style="color:#fff" target="_blank"><b><i><span style="font-size:18px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;text-decoration:none"><img border="0" width="46" height="43" src="http://loyegor.com/work/mail-template/img/twitter_my.png?ver=1.0.1" class=""></span></i></b></a><b><i><span lang="EN-CA" style="font-size:18px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d">  </span></i></b><a href="http://www.facebook.com/229000977160808" style="color:#474a5d" target="_blank"><b><i><span style="font-size:18px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;text-decoration:none"><img border="0" width="46" height="43" src="http://loyegor.com/work/mail-template/img/facebook_my.png?ver=1.0.1" class="CToWUd"></span></i></b></a><b><i><span lang="EN-CA" style="font-size:18px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d">  </span></i></b><a href="https://www.instagram.com/tree_doctors/" target="_blank" style="color: rgb(71, 74, 93);"><img border="0" width="43" height="43" src="' . $config['base_url'] . '/assets/img/instagram.png"></a></span></i></b></p><p style="font-size:18px;"><span style="font-size:24px;font-family:Webdings;color:#474a5d">P</span><span style="font-size:18px;font-family:AvenirNextLTPro-Regular, Arial,sans-serif;color:#474a5d"> </span><span style="font-size:12px;"><font color="#474a5d" face="Arial, sans-serif">please consider the environment before printing this email</font><font color="#474a5d" face="Arial, sans-serif"><u><br></u></font></span></p></td></tr></tbody></table><table width="100%" style="border-spacing:0;color:#474a5d;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;background-color:#5d863b;background-image:none;background-repeat:repeat;background-position:top left;background-attachment:scroll;"><tbody><tr><td class="inner contents" style="padding-top:20px;padding-bottom:10px;padding-right:30px;padding-left:30px;text-align:left;font-family:AvenirNext-Medium, Arial, \'Helvetica Neue\', Helvetica, sans-serif;color:#fff;"><span class="im"><p style="font-size:10px"><span style="font-size:9pt;font-family:AvenirNext-DemiBold,Arial,\'Helvetica Neue\',Helvetica,sans-serif;color:#fff">Privileged/Confidential Information may be contained in this message. If you are not the addressee indi<a style="color:#fff;text-decoration:none;">ca</a>ted in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such <a style="color:#fff;text-decoration:none;">ca</a>se, you should destroy this message and kindly notify the sender by reply email. Please advise immediately if you or your employer does not consent to email for messages of this kind.</span></p></span></td></tr></tbody></table>';
//$config['service_email_address'] = '729138097020-kd8mmg4ahah5u3bnqnefrcjo2v3hro6j@developer.gserviceaccount.com';
//$config['service_cert_path'] = './uploads/treedoctors-c6f443f9efc0.p12';
//$config['account_email_address'] = 'info@treedoctors.ca';

$config['qb_mode'] = 'development';
$config['qb_base_url'] = 'https://sandbox-quickbooks.api.intuit.com';

/* End of file config.php */
/* Location: ./application/config/config.php */
